- hosts: all
  user: ubuntu
  become: true
  gather_facts: False

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: all
  user: ubuntu
  become: true

  roles:
     - common

- hosts: frontend
  user: root

  roles:
    - nginx

- hosts: database
  user: root

  roles:
    - mysql


- hosts: backend
  user: root

  roles:
     - apache
     - php
     - wp-cli
     - wordpress
