---
- name: Update Apt
  apt: update_cache=yes

- name: Check if anything needs autoremoving
  shell: apt-get -y --dry-run autoremove | grep -q "0 to remove"
  register: check_autoremove
  ignore_errors: True
  changed_when: False
  check_mode:  no

- name: Autoremove unused packages
  command: apt-get -y autoremove
  when: "check_autoremove.rc != 0"

- name: Install system packages
  apt: name="{{ item }}" state=present
  with_items:
  - python-software-properties
  - python-pycurl
  - mysql-client
  - git-core
  - python-mysqldb 

- name: Add {{ remote_deploy_group }} group
  group:
    name: "{{ remote_deploy_group }}"

- name: Add {remote_deploy_user} user
  user:
    name: "{{ remote_deploy_user }}"
    home: "{{ remote_deploy_home }}"
    group: "{{ remote_deploy_group }}"

- name: Add ssh keys to root and deploy accounts
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', ssh_key_pub_path) }}"
  with_items:
  - root
  - "{{ remote_deploy_user }}"
